const Hiragana = [
  {
    id: 1,
    character: "あ",
    Romanji: "A",
    pronouncation: "ah",
    example: "Soft A sound, as the 'a' in 'father'",
  },
  {
    id: 2,
    character: "い",
    Romanji: "I",
    pronouncation: "ee",
    example: "Long E sound, as the 'ee' in 'meet.'",
  },
  {
    id: 3,
    character: "う",
    Romanji: "U",
    pronouncation: "oo",
    example: "Double O sound, as the 'oo' in 'boot.' ",
  },
  {
    id: 4,
    character: "え",
    Romanji: "E",
    pronouncation: "eh",
    example:
      "Short E or long A sound, as the “e” in “met.” It sometimes sounds like a “y” is in front of it 'ye.'",
  },
  {
    id: 5,
    character: "お",
    Romanji: "O",
    pronouncation: "oh",
    example: "Long O sound, as the 'o' in 'boat.'",
  },
  {
    id: 6,
    character: "か",
    Romanji: "KA",
    pronouncation: "Kah",
    example: "'Ca' in 'cause'",
  },
  {
    id: 7,
    character: "き",
    Romanji: "KI",
    pronouncation: "Kee",
    example: "Key",
  },
  {
    id: 8,
    character: "く",
    Romanji: "KU",
    pronouncation: "Koo",
    example: "Coo ",
  },
  {
    id: 9,
    character: "け",
    Romanji: "KE",
    pronouncation: "Keh",
    example: " 'Ke' in 'ketchup' ",
  },
  {
    id: 10,
    character: "こ",
    Romanji: "KO",
    pronouncation: "Koh",
    example: " 'Co' in 'Coat' ",
  },
  {
    id: 11,
    character: "さ",
    Romanji: "SA",
    pronouncation: "Sah",
    example: "Saw",
  },
  {
    id: 12,
    character: "し",
    Romanji: "SHI",
    pronouncation: "Shee",
    example: "She",
  },
  {
    id: 13,
    character: "す",
    Romanji: "SU",
    pronouncation: "Soo",
    example: "Sue",
  },
  {
    id: 14,
    character: "せ",
    Romanji: "SE",
    pronouncation: "Seh",
    example: " 'Se' in 'set' ",
  },
  {
    id: 15,
    character: "そ",
    Romanji: "SO",
    pronouncation: "Soh",
    example: "So",
  },
  {
    id: 16,
    character: "た",
    Romanji: "TA",
    pronouncation: "Tah",
    example: " 'Ta' in 'Tall' ",
  },
  {
    id: 17,
    character: "ち",
    Romanji: "CHI",
    pronouncation: "Chee",
    example: " 'Che' in 'Cheat' ",
  },
  {
    id: 18,
    character: "つ",
    Romanji: "TSU",
    pronouncation: "Tsoo",
    example: "'Tzu' in 'Shih Tzu' ",
  },
  {
    id: 19,
    character: "て",
    Romanji: "TE",
    pronouncation: "Teh",
    example: " 'Te' in 'Tell'",
  },
  {
    id: 20,
    character: "と",
    Romanji: "TO",
    pronouncation: "Toh",
    example: "Toe",
  },
  {
    id: 21,
    character: "な",
    Romanji: "NA",
    pronouncation: "Nah",
    example: " 'No' in 'not' ",
  },
  {
    id: 22,
    character: "に",
    Romanji: "NI",
    pronouncation: "Nee",
    example: "Knee",
  },
  {
    id: 23,
    character: "ぬ ",
    Romanji: "NU",
    pronouncation: "Noo",
    example: "New",
  },
  {
    id: 24,
    character: "ね",
    Romanji: "NE",
    pronouncation: "Neh",
    example: " 'Ne' in 'net' ",
  },
  {
    id: 25,
    character: "の",
    Romanji: "NO",
    pronouncation: "Noh",
    example: "No",
  },
  {
    id: 26,
    character: "は",
    Romanji: "HA",
    pronouncation: "Hah",
    example: "'Ha' in  'haunt' ",
  },
  {
    id: 27,
    character: "ひ",
    Romanji: "HI",
    pronouncation: "Hee",
    example: "HE",
  },
  {
    id: 28,
    character: "ふ",
    Romanji: "FU",
    pronouncation: "Foo",
    example:
      "This letter is produced by blowing through circular lips. It can be either “fu” or 'hu.'",
  },
  {
    id: 29,
    character: "へ",
    Romanji: "HE",
    pronouncation: "heh",
    example: " 'He' in 'head'",
  },
  {
    id: 30,
    character: "ほ",
    Romanji: "HO",
    pronouncation: "Hoh",
    example: "Hoe",
  },
  {
    id: 31,
    character: "ま",
    Romanji: "MA",
    pronouncation: "Mah",
    example: " 'Ma' in 'mall' ",
  },
  {
    id: 32,
    character: "み",
    Romanji: "MI",
    pronouncation: "Mee",
    example: "Me",
  },
  {
    id: 33,
    character: "む",
    Romanji: "MU",
    pronouncation: "Moo",
    example: " 'Moo' in 'Mood' ",
  },
  {
    id: 34,
    character: "め",
    Romanji: "ME",
    pronouncation: "Meh",
    example: "'Me' in 'met' ",
  },
  {
    id: 35,
    character: "も",
    Romanji: "MO",
    pronouncation: "Moh",
    example: " 'Mo' in 'most' ",
  },
  {
    id: 36,
    character: "や",
    Romanji: "YA",
    pronouncation: "Yah",
    example: "' ya' in 'yacht'",
  },
  {
    id: 37,
    character: "ゆ",
    Romanji: "YU",
    pronouncation: "Yoo",
    example: "You",
  },
  {
    id: 38,
    character: "よ",
    Romanji: "YO",
    pronouncation: "Yoh",
    example: " 'Yo' in 'yoke",
  },
  {
    id: 39,
    character: "ら",
    Romanji: "RA",
    pronouncation: "Rah",
    example: "",
  },
  {
    id: 40,
    character: "り",
    Romanji: "RI",
    pronouncation: "Ree",
    example: "",
  },
  {
    id: 41,
    character: "る",
    Romanji: "RU",
    pronouncation: "Roo",
    example: "",
  },
  {
    id: 42,
    character: "れ",
    Romanji: "RE",
    pronouncation: "Reh",
    example: "",
  },
  {
    id: 43,
    character: "ろ",
    Romanji: "RO",
    pronouncation: "Roh",
    example: "",
  },
  {
    id: 44,
    character: "わ",
    Romanji: "WA",
    pronouncation: "Wa",
    example: " 'Wa' in 'Want' ",
  },
  {
    id: 45,
    character: "を",
    Romanji: "WO",
    pronouncation: "(W)o",
    example:
      "This can be pronounced or spelled as either 'wo' as in 'wont' or “o” as in 'oat.'",
  },
  {
    id: 46,
    character: "ん",
    Romanji: "N",
    pronouncation: "n",
    example:
      "This can sound like the English N. Sometimes its a little softer and nasalized, like the nasalized N in French. When it precedes an M, B or P sound, it sounds like M (because the mouth is about to be closed in those letters).",
  },
];
export default Hiragana;
